name: icon-theme-elementary
build-base: core24
base: bare
version: '8'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: elementary and elementary-xfce icon theme
description: |
  A Snap that allows you to use elementary and elementary-xfce icons in Snap apps
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/elementary
        - $SNAP/share/icons/elementary-xfce
        - $SNAP/share/icons/elementary-xfce-dark
        - $SNAP/share/icons/elementary-xfce-darker
parts:
  elementary-os-icon-theme:
    plugin: dump
    source: https://github.com/Kyuyrii/icon-theme-elementary-snap/releases/download/icon-theme-elementary/elementary-icon-theme_8.1.0+r2788+pkg27.ubuntu8.1_all.deb
    organize:
      usr/share/icons: share/icons
    prime:
      - share/icons/elementary
  elementary-xfce-icon-theme:
    plugin: dump
    source: https://github.com/Kyuyrii/icon-theme-elementary-snap/releases/download/icon-theme-elementary/elementary-xfce-icon-theme_0.21-1_all.deb
    organize:
      usr/share/icons: share/icons
    prime:
      - share/icons/elementary-xfce
      - share/icons/elementary-xfce-dark
      - share/icons/elementary-xfce-hidpi
